### ISSUE TITLE
It's not loading 😂

### ISSUE THREAD

**Issue by jatin2003** [sindresorhus/sindresorhus#8] opened 2020-07-17 17:59 UTC
Hey @sindresorhus 

It looks like there's something wrong with repo as It seems to be always loading. It's not an Internet Problem from my side 😜

**Comment by sindresorhus** [comment] 2020-07-17 18:06
Try refreshing a couple of times. It loads eventually.

**Comment by palashmon** [comment] 2020-07-18 05:09
Duplicate of #1

**Comment by jatin2003** [comment] 2020-07-18 09:46
Oh! Issue [#1](https://github.com/sindresorhus/sindresorhus/issues/1) is the Same. So, I'm closing this Issue 💛

**Closed as completed** 2020-07-18 09:47 UTC
